# Generated by Django 5.0.3 on 2024-05-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_to_upload', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
