# Generated by Django 5.0.3 on 2024-05-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_encryptedfile_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to='encrypted/'),
        ),
    ]
